FROM golang:1.26rc2-alpine3.22 AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

FROM alpine:3.19
WORKDIR /app

COPY --from=build /app/worker .

CMD ["./worker"]
