FROM golang:1.26rc2-alpine3.22 AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build seed program from seed/seed.go
RUN CGO_ENABLED=0 GOOS=linux go build -o seed ./seed

FROM alpine:3.19
WORKDIR /app

COPY --from=build /app/seed .

CMD ["./seed"]
